languages:
- swift
encoding: "utf-8"

ignore_all_files_in_gitignore: true

ignored_paths: []

read_only: false

excluded_tools: []

initial_prompt: ""

project_name: "PantryPal"

included_optional_tools: []

memory: true
context_indexing: true
code_awareness: true
